server:
  port: ${PORT:8080}

spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGODB_DATABASE}

profile-service:
  url: ${PROFILE_SERVICE_URL}
  path: ${PROFILE_SERVICE_PATH}

geolocation-service:
  url: ${GEOLOCATION_SERVICE_URL}
  path: ${GEOLOCATION_SERVICE_PATH}

management:
  endpoints:
    web:
      exposure:
        include: health

feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 10000
